jobs:
  test-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki
        uses: actions/checkout@v3
        with:
          repository: Olaxee/OlaxeeTools.wiki.git
          path: wiki
          token: ${{ secrets.WIKI_TOKEN }}
      - name: List Wiki files
        run: ls wiki
